# Generated by Django 5.0.2 on 2024-03-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogcategory_postpageblogcategory_postpagetag_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postpagetag",
            old_name="content",
            new_name="content_object",
        ),
    ]
