# Generated by Django 5.0.2 on 2024-03-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_content_postpagetag_content_object"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postpageblogcategory",
            name="blog_category",
        ),
        migrations.AddField(
            model_name="postpage",
            name="blog_category",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_pages",
                to="blog.blogcategory",
            ),
            preserve_default=False,
        ),
    ]
